services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: Autoestopistamanco
      POSTGRES_PASSWORD: Fib49#7778742049
      POSTGRES_DB: customers
volumes:
  postgres_data:
